name: test_flutter
description: "Teste para vaga de programador Flutter!"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  flutter_web_auth_2: ^4.1.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0
  flex_color_scheme: ^8.2.0
  flutter_svg_provider: ^1.0.7
  flutter_svg: ^2.2.0
  webview_flutter: ^4.13.0
  webview_flutter_web: ^0.2.3+4
  flutter_social_button: ^1.1.6+1
  brasil_fields: ^1.18.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imgs/logo.svg
    - assets/imgs/logo-white.svg
